### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by BitWuehler** [KeeeX/jpegfix#1]
I'm very sorry, if this question is dumb, but I can't get your script to run, because everytime it needs the esm module. I already installed node.js and the esm module, but nothing changes. I have not experience with js-files. Maybe you could give me a short explanation or a few keywords with that I can work trough own research. Would be wonderfull. Thanks for your work!

**Comment by CleyFaye** [comment]
Ah. It's a bit of an old tool that didn't get updated when we got decent support for ES-modules in node. Using the `esm` dependency clashes with recent versions of node, so there's that.

I pushed an update that remove that issue; you should be able to run this tool in multiple ways, depending on your needs. The README is also updated in that regard.

If you don't particularly want to tinker with the code, I suggest a global installation with `npm install -g @keeex/jpegfix`. That should work on most OSes.

**Comment by BitWuehler** [comment]
Wow, that was fast. Now it works. Thanks a lot!
